-- Unsupported response compression is also an image fetch failure, not a DB/configuration outage.
CREATE OR REPLACE FUNCTION collect.image_failure_code(code text) RETURNS boolean LANGUAGE sql IMMUTABLE
SET search_path=pg_catalog AS $$ SELECT code=ANY(ARRAY[
 'ROBOTS_UNVERIFIED','ROBOTS_DISALLOWED','ROBOTS_DELAY_UNSUPPORTED','SOURCE_ACCESS_BLOCKED',
 'SOURCE_DNS_FAILED','SOURCE_FETCH_FAILED','SOURCE_GONE','SOURCE_HTTP_REJECTED','SOURCE_HTTP_UNAVAILABLE',
 'SOURCE_NOT_ALLOWED','SOURCE_RATE_LIMITED','SOURCE_REDIRECT_BLOCKED','SOURCE_REDIRECT_LOOP',
 'SOURCE_TOO_LARGE','SOURCE_MEDIA_TOTAL_LIMIT_EXCEEDED','SOURCE_NOT_IMAGE','SOURCE_URL_INVALID',
 'SOURCE_DNS_BLOCKED','SOURCE_ADDRESS_BLOCKED','SOURCE_ENCODING_UNSUPPORTED']) $$;
