export default defineNuxtConfig({
  compatibilityDate: '2026-09-07',
  devtools: { enabled: false },
  runtimeConfig: {
    coreOrigin: 'http://127.0.0.1:3100',
    trustedClientIpHeader: '',
    adminAuthMode: 'access',
    localAdminToken: '',
    serviceToken: '',
    actorSecret: '',
    accessIssuer: '',
    accessAudience: '',
    adminOperatorsFile: '',
    public: {
      siteOrigin: 'http://localhost:3000',
      siteName: '블라리요',
      homeTagline: '블라블라블라',
      homeTitle: '블라리요 - 블라블라블라',
      homeDescription: '블라리요에서 블라블라블라',
      homeOgDescription: '블라리요에서 블라블라블라',
      footerTagline: '블라블라블라',
      analyticsEnabled: false,
      analyticsApproved: false,
      measurementId: '',
      analyticsConnectOrigins: '',
      imageOrigin: '',
      rightsEmail: '',
      contactEmail: '',
      privacyEmail: '',
      privacyOfficer: '',
      operatorDisplayName: '',
      kakaoEnabled: false,
      kakaoKey: '',
      kakaoSdkUrl: '',
      kakaoIntegrity: '',
      kakaoConnectOrigins: '',
    },
  },
});
