import test from 'node:test';
import assert from 'node:assert/strict';
import { expect } from '@playwright/test';
import { browserFixture } from '../helpers/browser-fixture.ts';
import { launchBrowser } from '../helpers/launch-browser.ts';
await test('common codes: login return, create, rename, conflict, lost response and filter propagation', {timeout:90000}, async t => {
  const f=await browserFixture(t,{batchReview:true});
  const browser=await launchBrowser(); t.after(()=>browser.close());
  const context=await browser.newContext(), page=await context.newPage();
  await page.goto(f.origin+'/admin/source-codes');
  await page.getByRole('button',{name:'개발 관리자 로그인'}).click();
  await expect(page).toHaveURL(f.origin+'/admin/common-codes');
  await expect(page.getByRole('heading',{name:'출처 코드 21개'})).toBeVisible();
  await page.getByLabel('코드',{exact:true}).fill('test');
  await page.getByLabel('코드명',{exact:true}).fill('브라우저 출처');
  await page.getByLabel('수집 연결 식별자',{exact:true}).fill('browser-source');
  await page.getByRole('button',{name:'코드 등록',exact:true}).click();
  await expect(page.getByRole('status')).toHaveText('코드를 등록했습니다.');
  await page.getByRole('button',{name:'브라우저 출처 수정',exact:true}).click();
  await expect(page.getByLabel('코드',{exact:true})).toHaveAttribute('readonly','');
  await page.getByLabel('코드명',{exact:true}).fill('변경된 출처');
  await page.getByRole('button',{name:'수정 저장'}).click();
  await expect(page.getByRole('status')).toHaveText('코드명을 수정했습니다.');
  await page.getByRole('button',{name:'변경된 출처 수정',exact:true}).click();
  const endpoint=f.origin+'/api/v1/admin/common-code-groups/source/codes/test';
  assert.equal((await context.request.patch(endpoint,{headers:{Origin:f.origin},data:{displayName:'다른 관리자의 이름',lockVersion:2}})).status(),200);
  await page.getByLabel('코드명',{exact:true}).fill('내 입력 보존');
  await page.getByRole('button',{name:'수정 저장'}).click();
  await expect(page.getByRole('alert')).toContainText('다른 변경이 먼저 저장');
  await expect(page.getByLabel('코드명',{exact:true})).toHaveValue('내 입력 보존');
  await page.getByRole('button',{name:'최신 목록 다시 조회'}).click();
  await page.getByRole('button',{name:'다른 관리자의 이름 수정',exact:true}).click();
  await page.getByLabel('코드명',{exact:true}).fill('공통 출처명');
  await page.route('**/api/v1/admin/common-code-groups/source/codes/test',async route=>{
    if(route.request().method()==='PATCH'){await route.fetch();await route.abort('connectionreset');}else await route.continue();
  });
  await page.getByRole('button',{name:'수정 저장'}).click();
  await expect(page.getByRole('alert')).toContainText('저장 결과를 확인하지 못했습니다');
  await page.unroute('**/api/v1/admin/common-code-groups/source/codes/test');
  await page.getByRole('button',{name:'최신 목록 다시 조회'}).click();
  await expect(page.getByRole('button',{name:'공통 출처명 수정',exact:true})).toBeVisible();
  await page.getByRole('link',{name:'수집 결과 검수',exact:true}).click();
  const sources=page.getByRole('combobox',{name:'출처',exact:true});
  await expect(sources.locator('option[value="browser-source"]')).toHaveText('공통 출처명');
  await expect(sources.locator('option[value="theqoo"]')).toHaveText('더쿠');
  await sources.selectOption('browser-source');
  const queried=page.waitForRequest(request=>request.url().includes('/batch-items?')&&request.url().includes('source=browser-source'));
  await page.getByRole('button',{name:'조회',exact:true}).click(); await queried;
  await expect(page.getByText('조건에 맞는 수집 결과가 없습니다.')).toBeVisible();
  await page.getByRole('link',{name:'공통코드 관리',exact:true}).click();
  await page.getByRole('button',{name:'그룹 추가',exact:true}).click();
  await page.getByLabel('그룹 키',{exact:true}).fill('sample');
  await page.getByLabel('그룹명',{exact:true}).fill('샘플');
  await page.getByRole('button',{name:'그룹 저장',exact:true}).click();
  await expect(page.getByRole('status')).toHaveText('그룹을 저장했습니다.');
  await page.getByLabel('코드 그룹',{exact:true}).selectOption('sample');
  await expect(page.getByRole('heading',{name:'샘플 코드 0개'})).toBeVisible();
  await expect(page.getByLabel('수집 연결 식별자',{exact:true})).toHaveCount(0);
  await page.getByLabel('코드',{exact:true}).fill('test');
  await page.getByLabel('코드명',{exact:true}).fill('다른 그룹 코드');
  await page.getByRole('button',{name:'코드 등록',exact:true}).click();
  await expect(page.getByRole('button',{name:'다른 그룹 코드 수정',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'그룹명 수정',exact:true}).click();
  await page.getByLabel('그룹명',{exact:true}).fill('별도 그룹');
  await page.getByRole('button',{name:'그룹 저장',exact:true}).click();
  await expect(page.getByRole('heading',{name:'별도 그룹 코드 1개'})).toBeVisible();
  await page.getByLabel('코드 그룹',{exact:true}).selectOption('source');
  await expect(page.getByRole('button',{name:'공통 출처명 수정',exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:'다른 그룹 코드 수정',exact:true})).toHaveCount(0);
  for(const [code,name] of Object.entries({thqo:'더쿠',pmpu:'뽐뿌',yldo:'율도',invn:'인벤',dgdp:'개드립',rlwb:'루리웹'}))
    await expect(page.getByRole('row').filter({has:page.getByRole('cell',{name:code,exact:true})})).toContainText(name);
  for(const width of [1280,390,320]){
    await page.setViewportSize({width,height:900});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  }
});
