CREATE SCHEMA content;
CREATE SCHEMA legal;
CREATE SCHEMA IF NOT EXISTS ops;
CREATE TABLE content.board (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 slug VARCHAR(32) NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
 display_name VARCHAR(50) NOT NULL CHECK (length(trim(display_name)) BETWEEN 1 AND 50),
 is_active BOOLEAN NOT NULL, posting_policy VARCHAR(16) NOT NULL CHECK (posting_policy IN ('ADMIN','USER')),
 display_order SMALLINT NOT NULL UNIQUE CHECK (display_order >= 0)
);
CREATE INDEX ix_board__active_order ON content.board(is_active,display_order);
CREATE FUNCTION content.keep_board_slug() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF NEW.slug <> OLD.slug THEN RAISE EXCEPTION 'immutable board slug' USING ERRCODE='23514'; END IF; RETURN NEW; END $$;
CREATE TRIGGER board_slug_immutable BEFORE UPDATE ON content.board FOR EACH ROW EXECUTE FUNCTION content.keep_board_slug();
CREATE TABLE content.board_post (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 board_id BIGINT NOT NULL REFERENCES content.board(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
 title VARCHAR(200) NOT NULL CHECK(length(trim(title)) BETWEEN 1 AND 200),
 source_name VARCHAR(200), source_url VARCHAR(2048),
 status VARCHAR(20) NOT NULL CHECK(status IN ('DRAFT','SCHEDULED','PUBLISHED','HIDDEN_REVIEW','REMOVED')),
 pinned_position SMALLINT CHECK(pinned_position BETWEEN 1 AND 3), scheduled_at TIMESTAMPTZ(3), published_at TIMESTAMPTZ(3),
 view_count BIGINT NOT NULL DEFAULT 0 CHECK(view_count>=0), lock_version INTEGER NOT NULL DEFAULT 1 CHECK(lock_version>=1),
 CHECK(pinned_position IS NULL OR status IN ('DRAFT','SCHEDULED','PUBLISHED')),
 CHECK((source_name IS NULL)=(source_url IS NULL)),
 CHECK(source_name IS NULL OR length(trim(source_name)) BETWEEN 1 AND 200), CHECK(source_url IS NULL OR source_url ~ '^https://'),
 CHECK((status='DRAFT' AND scheduled_at IS NULL AND published_at IS NULL) OR
 (status='SCHEDULED' AND scheduled_at IS NOT NULL AND published_at IS NULL) OR
 (status IN ('PUBLISHED','HIDDEN_REVIEW','REMOVED') AND scheduled_at IS NULL AND published_at IS NOT NULL))
);
CREATE UNIQUE INDEX uq_board_post__active_pin ON content.board_post(board_id,pinned_position) WHERE status IN ('SCHEDULED','PUBLISHED') AND pinned_position IS NOT NULL;
CREATE INDEX ix_board_post__public ON content.board_post(board_id,published_at DESC,id DESC) WHERE status='PUBLISHED';
CREATE INDEX ix_board_post__scheduled ON content.board_post(scheduled_at,id) WHERE status='SCHEDULED';
CREATE TABLE content.board_post_image (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, post_id BIGINT REFERENCES content.board_post(id) ON DELETE RESTRICT,
 private_storage_key VARCHAR(512) NOT NULL UNIQUE, public_storage_key VARCHAR(512),
 status VARCHAR(24) NOT NULL CHECK(status IN ('STAGED','PUBLIC','PUBLIC_DELETE_PENDING','PRIVATE_REVIEW','PRIVATE_DELETE_PENDING','DELETED')),
 content_sha256 BYTEA NOT NULL CHECK(octet_length(content_sha256)=32), mime_type VARCHAR(50) NOT NULL,
 byte_size INTEGER NOT NULL CHECK(byte_size>0), width INTEGER NOT NULL CHECK(width>0), height INTEGER NOT NULL CHECK(height>0),
 UNIQUE(post_id,id),
 CHECK((status IN ('PUBLIC','PUBLIC_DELETE_PENDING') AND public_storage_key IS NOT NULL) OR (status IN ('STAGED','PRIVATE_REVIEW','PRIVATE_DELETE_PENDING','DELETED') AND public_storage_key IS NULL)),
 CHECK(post_id IS NOT NULL OR status IN ('STAGED','PRIVATE_DELETE_PENDING','DELETED'))
);
CREATE UNIQUE INDEX uq_board_post_image__public_key ON content.board_post_image(public_storage_key) WHERE public_storage_key IS NOT NULL;
CREATE INDEX ix_board_post_image__content_sha256 ON content.board_post_image(content_sha256);
CREATE TABLE content.board_post_block (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, post_id BIGINT NOT NULL REFERENCES content.board_post(id) ON DELETE RESTRICT,
 position SMALLINT NOT NULL CHECK(position>=1), type VARCHAR(16) NOT NULL CHECK(type IN ('TEXT','IMAGE')),
 text_content TEXT CHECK(text_content IS NULL OR length(trim(text_content)) BETWEEN 1 AND 20000), image_id BIGINT,
 alt_text VARCHAR(300) CHECK(alt_text IS NULL OR length(trim(alt_text)) BETWEEN 1 AND 300),
 FOREIGN KEY(post_id,image_id) REFERENCES content.board_post_image(post_id,id) ON DELETE RESTRICT,
 UNIQUE(post_id,position),
 CHECK((type='TEXT' AND text_content IS NOT NULL AND image_id IS NULL AND alt_text IS NULL) OR
 (type='IMAGE' AND text_content IS NULL AND image_id IS NOT NULL AND alt_text IS NOT NULL))
);
CREATE UNIQUE INDEX uq_board_post_block__image ON content.board_post_block(image_id) WHERE image_id IS NOT NULL;
CREATE TABLE content.board_post_status_history (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, post_id BIGINT NOT NULL REFERENCES content.board_post(id) ON DELETE RESTRICT,
 from_status VARCHAR(20) CHECK(from_status IN ('DRAFT','SCHEDULED','PUBLISHED','HIDDEN_REVIEW','REMOVED')),
 to_status VARCHAR(20) NOT NULL CHECK(to_status IN ('DRAFT','SCHEDULED','PUBLISHED','HIDDEN_REVIEW','REMOVED')),
 reason_code VARCHAR(30) NOT NULL CHECK(reason_code IN ('CREATE','EDIT','SCHEDULE','PUBLISH','UNSCHEDULE','RIGHTS_EMAIL','REPUBLISH','REMOVE','SYSTEM_DUE','PINNED_ORDER_CONFLICT')),
 actor_type VARCHAR(16) NOT NULL CHECK(actor_type IN ('ADMIN','SYSTEM'))
);
CREATE TABLE legal.policy_version (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 policy_type VARCHAR(20) NOT NULL CHECK(policy_type IN ('TERMS','PRIVACY')), version_label VARCHAR(20) NOT NULL,
 title VARCHAR(200) NOT NULL CHECK(length(trim(title)) BETWEEN 1 AND 200), body_html TEXT NOT NULL CHECK(length(trim(body_html))>0),
 status VARCHAR(20) NOT NULL CHECK(status IN ('DRAFT','EFFECTIVE','RETIRED')), effective_at TIMESTAMPTZ(3), ended_at TIMESTAMPTZ(3),
 UNIQUE(policy_type,version_label),
 CHECK((status='DRAFT' AND effective_at IS NULL AND ended_at IS NULL) OR
 (status='EFFECTIVE' AND effective_at IS NOT NULL AND ended_at IS NULL) OR
 (status='RETIRED' AND effective_at IS NOT NULL AND ended_at IS NOT NULL AND ended_at>effective_at))
);
CREATE UNIQUE INDEX uq_policy_version__effective_one ON legal.policy_version(policy_type) WHERE status='EFFECTIVE';
CREATE INDEX ix_policy_version__type_status_effective ON legal.policy_version(policy_type,status,effective_at DESC);
CREATE TABLE ops.outbox_task (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 type VARCHAR(30) NOT NULL CHECK(type IN ('CACHE_PURGE','OBJECT_DELETE_PUBLIC','OBJECT_DELETE_PRIVATE')),
 status VARCHAR(20) NOT NULL CHECK(status IN ('PENDING','RUNNING','SUCCEEDED','FAILED','DEAD')),
 aggregate_type VARCHAR(20) NOT NULL CHECK(aggregate_type IN ('POST','IMAGE','POLICY','STORAGE_OBJECT')), aggregate_id BIGINT,
 payload JSONB NOT NULL CHECK(jsonb_typeof(payload)='object'), attempt_count SMALLINT NOT NULL DEFAULT 0 CHECK(attempt_count BETWEEN 0 AND 8),
 next_attempt_at TIMESTAMPTZ(3) NOT NULL, last_error_code VARCHAR(50),
 CHECK((type='CACHE_PURGE' AND aggregate_type IN ('POST','POLICY')) OR
 (type IN ('OBJECT_DELETE_PUBLIC','OBJECT_DELETE_PRIVATE') AND aggregate_type='IMAGE') OR (type='OBJECT_DELETE_PRIVATE' AND aggregate_type='STORAGE_OBJECT')),
 CHECK((aggregate_type IN ('POST','IMAGE','POLICY') AND aggregate_id IS NOT NULL AND aggregate_id>0) OR (aggregate_type='STORAGE_OBJECT' AND aggregate_id IS NULL))
);
CREATE INDEX ix_outbox_task__due ON ops.outbox_task(next_attempt_at,id) WHERE status IN ('PENDING','FAILED');
CREATE TABLE ops.idempotency_request (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, operation_scope VARCHAR(120) NOT NULL, idempotency_key VARCHAR(128) NOT NULL,
 request_hash BYTEA NOT NULL CHECK(octet_length(request_hash)=32), response_status SMALLINT NOT NULL CHECK(response_status BETWEEN 200 AND 299),
 response_body JSONB NOT NULL CHECK(jsonb_typeof(response_body)='object'), resource_type VARCHAR(20) NOT NULL CHECK(resource_type='POST'),
 resource_id BIGINT NOT NULL CHECK(resource_id>0), expires_at TIMESTAMPTZ(3) NOT NULL
);
-- Apply the same audit contract to every domain table, with no implicit actor default.
DO $$ DECLARE t TEXT; BEGIN
 FOREACH t IN ARRAY ARRAY['content.board','content.board_post','content.board_post_image','content.board_post_block','content.board_post_status_history','legal.policy_version','ops.outbox_task','ops.idempotency_request'] LOOP
 EXECUTE format('ALTER TABLE %s ADD created_by VARCHAR(100) NOT NULL, ADD created_at TIMESTAMPTZ(3) NOT NULL, ADD updated_by VARCHAR(100) NOT NULL, ADD updated_at TIMESTAMPTZ(3) NOT NULL',t);
 EXECUTE format('ALTER TABLE %s ADD CHECK(created_by ~ %L), ADD CHECK(updated_by ~ %L), ADD CHECK(updated_at>=created_at)',t,
 '^(system:(migration|scheduler|policy-publisher|outbox-worker|collector)|(admin|user):v[1-9][0-9]*:[A-Za-z0-9_-]{43})$',
 '^(system:(migration|scheduler|policy-publisher|outbox-worker|collector)|(admin|user):v[1-9][0-9]*:[A-Za-z0-9_-]{43})$');
 END LOOP;
END $$;
ALTER TABLE ops.idempotency_request ADD CONSTRAINT uq_idempotency_request__actor_scope_key UNIQUE(created_by,operation_scope,idempotency_key), ADD CHECK(expires_at>created_at);
CREATE INDEX ix_idempotency_request__expires ON ops.idempotency_request(expires_at);
CREATE INDEX ix_idempotency_request__resource ON ops.idempotency_request(resource_type,resource_id,created_at DESC);
CREATE INDEX ix_board_post__updated ON content.board_post(updated_at,id);
CREATE INDEX ix_board_post_image__status_updated ON content.board_post_image(status,updated_at);
CREATE INDEX ix_board_post_status_history__post_created ON content.board_post_status_history(post_id,created_at DESC);
CREATE INDEX ix_board_post_status_history__reason_created ON content.board_post_status_history(reason_code,created_at DESC);
CREATE INDEX ix_outbox_task__running ON ops.outbox_task(updated_at,id) WHERE status='RUNNING';
CREATE FUNCTION ops.is_schema_ready(expected_version TEXT) RETURNS BOOLEAN LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog AS $$
 SELECT COALESCE((SELECT version=expected_version FROM ops.schema_migration ORDER BY substring(version FROM 2)::integer DESC LIMIT 1),false)
$$;
REVOKE ALL ON FUNCTION ops.is_schema_ready(TEXT) FROM PUBLIC;
