CREATE SCHEMA collect;
CREATE TABLE collect.source (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL, base_url VARCHAR(2048) NOT NULL CHECK(base_url ~ '^https://'),
    host VARCHAR(255) NOT NULL UNIQUE CHECK(host=lower(host) AND length(host)>=3),
    fetch_mode VARCHAR(16) NOT NULL DEFAULT 'URL_ONLY' CHECK(fetch_mode='URL_ONLY'),
    list_url VARCHAR(2048) CHECK(list_url IS NULL),
    parser_type VARCHAR(24) NOT NULL DEFAULT 'MANUAL' CHECK(parser_type='MANUAL'),
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    is_list_crawl_enabled BOOLEAN NOT NULL DEFAULT FALSE CHECK(NOT is_list_crawl_enabled),
    robots_allowed BOOLEAN, robots_checked_at TIMESTAMPTZ(3),
    request_interval_ms INTEGER NOT NULL CHECK(request_interval_ms>=1000),
    daily_fetch_limit INTEGER NOT NULL CHECK(daily_fetch_limit BETWEEN 1 AND 10000),
    last_fetched_at TIMESTAMPTZ(3),
    last_error_code VARCHAR(50),
    consecutive_error_count INTEGER NOT NULL DEFAULT 0 CHECK(consecutive_error_count>=0),
    disabled_reason_code VARCHAR(30) CHECK(
        disabled_reason_code IN ('ROBOTS_DISALLOWED','BLOCKED','FETCH_ERROR','OPERATOR')
    ),
    lock_version INTEGER NOT NULL DEFAULT 1 CHECK(lock_version>=1),
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    updated_by VARCHAR(100) NOT NULL, updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    CHECK((robots_allowed IS NULL)=(robots_checked_at IS NULL))
);
CREATE TABLE collect.candidate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, source_id BIGINT NOT NULL REFERENCES collect.source(id),
    origin_url VARCHAR(2048) NOT NULL CHECK(origin_url ~ '^https://'),
    origin_url_sha256 BYTEA NOT NULL UNIQUE CHECK(octet_length(origin_url_sha256)=32),
    title VARCHAR(300) CHECK(length(trim(title)) BETWEEN 1 AND 300), source_published_at TIMESTAMPTZ(3),
    parser_version VARCHAR(100) CHECK(length(trim(parser_version)) BETWEEN 1 AND 100),
    warnings JSONB NOT NULL DEFAULT '[]' CHECK(jsonb_typeof(warnings)='array' AND jsonb_array_length(warnings)<=20),
    status VARCHAR(16) NOT NULL CHECK(status IN ('PENDING','RUNNING','NEW','FETCH_FAILED','APPROVED','REJECTED')),
    discovery_mode VARCHAR(16) NOT NULL DEFAULT 'MANUAL_URL' CHECK(discovery_mode='MANUAL_URL'),
    duplicate_post_id BIGINT REFERENCES content.board_post(id), post_id BIGINT REFERENCES content.board_post(id),
    reject_reason_code VARCHAR(30) CHECK(
        reject_reason_code IN ('DUPLICATE','LOW_QUALITY','RIGHTS_RISK','NOT_FUNNY','SOURCE_GONE','OTHER')
    ),
    fetch_error_code VARCHAR(50), collector_id VARCHAR(100), requested_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    claimed_at TIMESTAMPTZ(3), lease_until TIMESTAMPTZ(3), fetched_at TIMESTAMPTZ(3), reviewed_at TIMESTAMPTZ(3),
    attempt_count INTEGER NOT NULL DEFAULT 0 CHECK(attempt_count>=0),
    lock_version INTEGER NOT NULL DEFAULT 1 CHECK(lock_version>=1),
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    updated_by VARCHAR(100) NOT NULL, updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    CHECK(status NOT IN ('NEW','APPROVED') OR (parser_version IS NOT NULL AND title IS NOT NULL)),
    CHECK(
        (status='APPROVED' AND post_id IS NOT NULL AND reviewed_at IS NOT NULL AND reject_reason_code IS NULL)
        OR (status='REJECTED' AND post_id IS NULL AND reviewed_at IS NOT NULL AND reject_reason_code IS NOT NULL)
        OR (
            status IN ('PENDING','RUNNING','NEW','FETCH_FAILED')
            AND post_id IS NULL
            AND reviewed_at IS NULL
            AND reject_reason_code IS NULL
        )
    ),
    CHECK(status<>'FETCH_FAILED' OR fetch_error_code IS NOT NULL),
    CHECK(status<>'RUNNING' OR (collector_id IS NOT NULL AND claimed_at IS NOT NULL AND lease_until IS NOT NULL)),
    CHECK(status='RUNNING' OR lease_until IS NULL),
    CHECK((status IN ('PENDING','RUNNING'))=(fetched_at IS NULL))
);
CREATE TABLE collect.candidate_image (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id BIGINT NOT NULL REFERENCES collect.candidate(id),
    position SMALLINT NOT NULL CHECK(position BETWEEN 1 AND 20),
    remote_url VARCHAR(2048) NOT NULL CHECK(remote_url ~ '^https://'),
    preview_storage_key VARCHAR(500), preview_expires_at TIMESTAMPTZ(3),
    image_id BIGINT REFERENCES content.board_post_image(id),
    status VARCHAR(16) NOT NULL DEFAULT 'DISCOVERED' CHECK(status IN ('DISCOVERED','STORED','SKIPPED','FAILED')),
    fetch_error_code VARCHAR(50), created_by VARCHAR(100) NOT NULL, created_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    updated_by VARCHAR(100) NOT NULL, updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT now(), UNIQUE(candidate_id,position),
    CHECK((status='STORED')=(image_id IS NOT NULL)), CHECK((preview_storage_key IS NULL)=(preview_expires_at IS NULL)),
    CHECK(status<>'FAILED' OR fetch_error_code IS NOT NULL)
);
CREATE UNIQUE INDEX uq_collect_candidate__post ON collect.candidate(post_id) WHERE post_id IS NOT NULL;
CREATE UNIQUE INDEX uq_collect_candidate_image__image ON collect.candidate_image(image_id) WHERE image_id IS NOT NULL;
CREATE INDEX ix_collect_candidate__status_fetched ON collect.candidate(status,fetched_at DESC);
CREATE INDEX ix_collect_candidate__source_fetched ON collect.candidate(source_id,fetched_at DESC);
CREATE INDEX ix_collect_candidate__claimable ON collect.candidate(status,lease_until,requested_at) WHERE status IN (
    'PENDING','RUNNING'
);
ALTER TABLE ops.idempotency_request DROP CONSTRAINT idempotency_request_resource_type_check;
ALTER TABLE ops.idempotency_request ADD CONSTRAINT idempotency_request_resource_type_check CHECK(
    resource_type IN ('POST','CANDIDATE')
);
DO $$ DECLARE t TEXT; BEGIN
 FOREACH t IN ARRAY ARRAY['source','candidate','candidate_image'] LOOP
 EXECUTE format('ALTER TABLE collect.%I ADD CHECK(created_by ~ %L AND updated_by ~ %L)',t,
 '^(system:(migration|scheduler|policy-publisher|outbox-worker|collector)|(admin|user):v[1-9][0-9]*:[A-Za-z0-9_-]{43})$',
 '^(system:(migration|scheduler|policy-publisher|outbox-worker|collector)|(admin|user):v[1-9][0-9]*:[A-Za-z0-9_-]{43})$');
 END LOOP; END $$;
-- No external sources are seeded before source-specific approval and validation.
