-- 개발 연결 확인용 레거시 회원 스키마다.
-- M0 운영 스키마의 정본이 아니며 운영 환경에서는 V001/V002 migration을 사용한다.

SET TIME ZONE 'UTC';

CREATE TABLE IF NOT EXISTS tc_code_group (
    code_group VARCHAR(20) PRIMARY KEY,
    code_group_nm VARCHAR(100) NOT NULL,
    code_group_desc VARCHAR(500),
    use_yn CHAR(1) NOT NULL DEFAULT 'Y' CHECK (use_yn IN ('Y', 'N')),
    sort_ord INTEGER NOT NULL DEFAULT 0 CHECK (sort_ord >= 0),
    creator_no BIGINT,
    reg_dttm TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updator_no BIGINT,
    upd_dttm TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tc_code (
    code_group VARCHAR(20) NOT NULL,
    code VARCHAR(20) NOT NULL,
    code_nm VARCHAR(100) NOT NULL,
    code_desc VARCHAR(500),
    parent_code VARCHAR(20),
    use_yn CHAR(1) NOT NULL DEFAULT 'Y' CHECK (use_yn IN ('Y', 'N')),
    sort_ord INTEGER NOT NULL DEFAULT 0 CHECK (sort_ord >= 0),
    creator_no BIGINT,
    reg_dttm TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updator_no BIGINT,
    upd_dttm TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (code_group, code),
    FOREIGN KEY (code_group) REFERENCES tc_code_group(code_group),
    FOREIGN KEY (code_group, parent_code) REFERENCES tc_code(code_group, code)
);

CREATE TABLE IF NOT EXISTS tu_user (
    user_no BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL UNIQUE,
    user_pswd VARCHAR(255) NOT NULL,
    user_nm VARCHAR(100) NOT NULL,
    email VARCHAR(100),
    role_code VARCHAR(20) NOT NULL CHECK (role_code IN ('GST', 'USR', 'ADM', 'SAD')),
    status_code VARCHAR(20) NOT NULL CHECK (status_code IN ('ACT', 'DOR', 'LCK', 'WDR', 'FWD')),
    pwd_rst_tkn VARCHAR(100),
    login_fail_cnt SMALLINT NOT NULL DEFAULT 0 CHECK (login_fail_cnt BETWEEN 0 AND 5),
    reg_dttm TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updator_no BIGINT REFERENCES tu_user(user_no),
    upd_dttm TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lst_accss_dttm TIMESTAMPTZ(3)
);

CREATE INDEX IF NOT EXISTS idx_tu_user_email ON tu_user(email);
CREATE INDEX IF NOT EXISTS idx_tu_user_status ON tu_user(status_code);
CREATE INDEX IF NOT EXISTS idx_tu_user_pwd_rst_tkn ON tu_user(pwd_rst_tkn);

INSERT INTO tc_code_group (code_group, code_group_nm, code_group_desc)
VALUES
    ('USR_ROLE', '사용자 권한', '사용자의 권한을 나타내는 코드'),
    ('USR_STAT', '사용자 상태', '사용자의 상태를 나타내는 코드')
ON CONFLICT (code_group) DO NOTHING;

INSERT INTO tc_code (code_group, code, code_nm, code_desc)
VALUES
    ('USR_ROLE', 'GST', '비회원', '비회원 사용자'),
    ('USR_ROLE', 'USR', '일반 사용자', '일반 사용자'),
    ('USR_ROLE', 'ADM', '관리자', '시스템 관리자'),
    ('USR_ROLE', 'SAD', '슈퍼 관리자', '최고 관리자'),
    ('USR_STAT', 'ACT', '활성', '정상 사용 중인 상태'),
    ('USR_STAT', 'DOR', '휴면', '장기간 미접속 상태'),
    ('USR_STAT', 'LCK', '잠금', '비밀번호 5회 이상 실패로 인한 계정 잠금 상태'),
    ('USR_STAT', 'WDR', '탈퇴', '사용자가 직접 탈퇴한 상태'),
    ('USR_STAT', 'FWD', '강제 탈퇴', '관리자가 강제로 탈퇴시킨 상태')
ON CONFLICT (code_group, code) DO NOTHING;

INSERT INTO tu_user (user_id, user_pswd, user_nm, email, role_code, status_code)
VALUES
    ('user1', '$2b$10$1YC8DMQqbXfaZrIVVNa7.OPn0HFw7QIp8bGcPQFQNLzR0IQF3OyIi', '사용자1', 'user1@example.com', 'USR', 'ACT'),
    ('admin1', '$2b$10$1YC8DMQqbXfaZrIVVNa7.OPn0HFw7QIp8bGcPQFQNLzR0IQF3OyIi', '관리자1', 'admin1@example.com', 'ADM', 'ACT'),
    ('superadmin', '$2b$10$1YC8DMQqbXfaZrIVVNa7.OPn0HFw7QIp8bGcPQFQNLzR0IQF3OyIi', '슈퍼관리자', 'superadmin@example.com', 'SAD', 'ACT')
ON CONFLICT (user_id) DO NOTHING;
