SET TIME ZONE 'UTC';

CREATE SCHEMA IF NOT EXISTS content;
CREATE SCHEMA IF NOT EXISTS legal;
CREATE SCHEMA IF NOT EXISTS analytics;
CREATE SCHEMA IF NOT EXISTS ops;

CREATE TABLE content.board (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug VARCHAR(32) NOT NULL,
  display_name VARCHAR(50) NOT NULL,
  is_active BOOLEAN NOT NULL,
  posting_policy VARCHAR(16) NOT NULL,
  display_order SMALLINT NOT NULL,
  created_by VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(100) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_board__slug UNIQUE (slug),
  CONSTRAINT uq_board__display_order UNIQUE (display_order),
  CONSTRAINT ck_board__slug CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  CONSTRAINT ck_board__display_name CHECK (length(btrim(display_name)) BETWEEN 1 AND 50),
  CONSTRAINT ck_board__posting_policy CHECK (posting_policy IN ('ADMIN', 'USER')),
  CONSTRAINT ck_board__display_order CHECK (display_order >= 0),
  CONSTRAINT ck_board__created_by CHECK (created_by ~ '^(system:(migration|scheduler|event-ingest|event-aggregate|outbox-worker)|(admin|user):v[1-9][0-9]*:[A-Za-z0-9_-]{43})$'),
  CONSTRAINT ck_board__updated_by CHECK (updated_by ~ '^(system:(migration|scheduler|event-ingest|event-aggregate|outbox-worker)|(admin|user):v[1-9][0-9]*:[A-Za-z0-9_-]{43})$'),
  CONSTRAINT ck_board__audit_time CHECK (updated_at >= created_at)
);

CREATE INDEX ix_board__active_order ON content.board (is_active, display_order);

CREATE FUNCTION content.reject_board_slug_update()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.slug IS DISTINCT FROM OLD.slug THEN
    RAISE EXCEPTION 'board slug is immutable' USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_board__immutable_slug
BEFORE UPDATE OF slug ON content.board
FOR EACH ROW
EXECUTE FUNCTION content.reject_board_slug_update();

CREATE TABLE content.board_post (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  board_id BIGINT NOT NULL,
  title VARCHAR(200) NOT NULL,
  source_name VARCHAR(200),
  source_url VARCHAR(2048),
  status VARCHAR(20) NOT NULL,
  pinned_position SMALLINT,
  scheduled_at TIMESTAMPTZ(3),
  published_at TIMESTAMPTZ(3),
  view_count BIGINT NOT NULL DEFAULT 0,
  lock_version INTEGER NOT NULL DEFAULT 1,
  created_by VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(100) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_board_post__board FOREIGN KEY (board_id) REFERENCES content.board(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT ck_board_post__title CHECK (length(btrim(title)) BETWEEN 1 AND 200),
  CONSTRAINT ck_board_post__source_pair CHECK ((source_name IS NULL) = (source_url IS NULL)),
  CONSTRAINT ck_board_post__source_name CHECK (source_name IS NULL OR length(btrim(source_name)) BETWEEN 1 AND 200),
  CONSTRAINT ck_board_post__source_url CHECK (source_url IS NULL OR source_url ~ '^https://'),
  CONSTRAINT ck_board_post__status CHECK (status IN ('DRAFT', 'SCHEDULED', 'PUBLISHED', 'HIDDEN_REVIEW', 'REMOVED')),
  CONSTRAINT ck_board_post__pinned_position CHECK (pinned_position IS NULL OR pinned_position BETWEEN 1 AND 3),
  CONSTRAINT ck_board_post__pinned_status CHECK (pinned_position IS NULL OR status IN ('DRAFT', 'SCHEDULED', 'PUBLISHED')),
  CONSTRAINT ck_board_post__status_time CHECK (
    (status = 'DRAFT' AND scheduled_at IS NULL AND published_at IS NULL)
    OR (status = 'SCHEDULED' AND scheduled_at IS NOT NULL AND published_at IS NULL)
    OR (status IN ('PUBLISHED', 'HIDDEN_REVIEW', 'REMOVED') AND scheduled_at IS NULL AND published_at IS NOT NULL)
  ),
  CONSTRAINT ck_board_post__view_count CHECK (view_count >= 0),
  CONSTRAINT ck_board_post__lock_version CHECK (lock_version >= 1),
  CONSTRAINT ck_board_post__created_by CHECK (created_by ~ '^(system:(migration|scheduler|event-ingest|event-aggregate|outbox-worker)|(admin|user):v[1-9][0-9]*:[A-Za-z0-9_-]{43})$'),
  CONSTRAINT ck_board_post__updated_by CHECK (updated_by ~ '^(system:(migration|scheduler|event-ingest|event-aggregate|outbox-worker)|(admin|user):v[1-9][0-9]*:[A-Za-z0-9_-]{43})$'),
  CONSTRAINT ck_board_post__audit_time CHECK (updated_at >= created_at)
);

CREATE UNIQUE INDEX uq_board_post__published_pin
  ON content.board_post (board_id, pinned_position)
  WHERE status = 'PUBLISHED' AND pinned_position IS NOT NULL;
CREATE INDEX ix_board_post__public
  ON content.board_post (board_id, published_at DESC, id DESC)
  WHERE status = 'PUBLISHED';
CREATE INDEX ix_board_post__scheduled
  ON content.board_post (scheduled_at, id)
  WHERE status = 'SCHEDULED';
CREATE INDEX ix_board_post__updated ON content.board_post (updated_at, id);

CREATE TABLE content.board_post_image (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT,
  private_storage_key VARCHAR(512) NOT NULL,
  public_storage_key VARCHAR(512),
  status VARCHAR(24) NOT NULL,
  content_sha256 BYTEA NOT NULL,
  mime_type VARCHAR(50) NOT NULL,
  byte_size INTEGER NOT NULL,
  width INTEGER NOT NULL,
  height INTEGER NOT NULL,
  created_by VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(100) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_board_post_image__private_key UNIQUE (private_storage_key),
  CONSTRAINT uq_board_post_image__post_id_id UNIQUE (post_id, id),
  CONSTRAINT fk_board_post_image__post FOREIGN KEY (post_id) REFERENCES content.board_post(id) ON DELETE RESTRICT,
  CONSTRAINT ck_board_post_image__status CHECK (status IN ('STAGED', 'PUBLIC', 'PUBLIC_DELETE_PENDING', 'PRIVATE_REVIEW', 'PRIVATE_DELETE_PENDING', 'DELETED')),
  CONSTRAINT ck_board_post_image__content_sha256 CHECK (octet_length(content_sha256) = 32),
  CONSTRAINT ck_board_post_image__dimensions CHECK (byte_size > 0 AND width > 0 AND height > 0),
  CONSTRAINT ck_board_post_image__public_key_status CHECK (
    (status IN ('PUBLIC', 'PUBLIC_DELETE_PENDING') AND public_storage_key IS NOT NULL)
    OR (status IN ('STAGED', 'PRIVATE_REVIEW', 'PRIVATE_DELETE_PENDING', 'DELETED') AND public_storage_key IS NULL)
  ),
  CONSTRAINT ck_board_post_image__unowned_status CHECK (post_id IS NOT NULL OR status IN ('STAGED', 'PRIVATE_DELETE_PENDING', 'DELETED')),
  CONSTRAINT ck_board_post_image__created_by CHECK (created_by ~ '^(system:(migration|scheduler|event-ingest|event-aggregate|outbox-worker)|(admin|user):v[1-9][0-9]*:[A-Za-z0-9_-]{43})$'),
  CONSTRAINT ck_board_post_image__updated_by CHECK (updated_by ~ '^(system:(migration|scheduler|event-ingest|event-aggregate|outbox-worker)|(admin|user):v[1-9][0-9]*:[A-Za-z0-9_-]{43})$'),
  CONSTRAINT ck_board_post_image__audit_time CHECK (updated_at >= created_at)
);

CREATE UNIQUE INDEX uq_board_post_image__public_key
  ON content.board_post_image (public_storage_key)
  WHERE public_storage_key IS NOT NULL;
CREATE INDEX ix_board_post_image__content_sha256 ON content.board_post_image (content_sha256);
CREATE INDEX ix_board_post_image__status_updated ON content.board_post_image (status, updated_at);

CREATE TABLE content.board_post_block (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL,
  position SMALLINT NOT NULL,
  type VARCHAR(16) NOT NULL,
  text_content TEXT,
  image_id BIGINT,
  alt_text VARCHAR(300),
  created_by VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(100) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_board_post_block__position UNIQUE (post_id, position),
  CONSTRAINT fk_board_post_block__post FOREIGN KEY (post_id) REFERENCES content.board_post(id) ON DELETE RESTRICT,
  CONSTRAINT fk_board_post_block__owned_image FOREIGN KEY (post_id, image_id) REFERENCES content.board_post_image(post_id, id) ON DELETE RESTRICT,
  CONSTRAINT ck_board_post_block__position CHECK (position >= 1),
  CONSTRAINT ck_board_post_block__type CHECK (type IN ('TEXT', 'IMAGE')),
  CONSTRAINT ck_board_post_block__content CHECK (
    (type = 'TEXT' AND text_content IS NOT NULL AND image_id IS NULL AND alt_text IS NULL)
    OR (type = 'IMAGE' AND text_content IS NULL AND image_id IS NOT NULL AND alt_text IS NOT NULL)
  ),
  CONSTRAINT ck_board_post_block__text_content CHECK (text_content IS NULL OR length(btrim(text_content)) BETWEEN 1 AND 20000),
  CONSTRAINT ck_board_post_block__alt_text CHECK (alt_text IS NULL OR length(btrim(alt_text)) BETWEEN 1 AND 300),
  CONSTRAINT ck_board_post_block__created_by CHECK (created_by ~ '^(system:(migration|scheduler|event-ingest|event-aggregate|outbox-worker)|(admin|user):v[1-9][0-9]*:[A-Za-z0-9_-]{43})$'),
  CONSTRAINT ck_board_post_block__updated_by CHECK (updated_by ~ '^(system:(migration|scheduler|event-ingest|event-aggregate|outbox-worker)|(admin|user):v[1-9][0-9]*:[A-Za-z0-9_-]{43})$'),
  CONSTRAINT ck_board_post_block__audit_time CHECK (updated_at >= created_at)
);

CREATE UNIQUE INDEX uq_board_post_block__image
  ON content.board_post_block (image_id)
  WHERE image_id IS NOT NULL;

CREATE TABLE content.board_post_status_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL,
  from_status VARCHAR(20),
  to_status VARCHAR(20) NOT NULL,
  reason_code VARCHAR(30) NOT NULL,
  actor_type VARCHAR(16) NOT NULL,
  created_by VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(100) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_board_post_status_history__post FOREIGN KEY (post_id) REFERENCES content.board_post(id) ON DELETE RESTRICT,
  CONSTRAINT ck_board_post_status_history__reason CHECK (reason_code IN ('CREATE', 'EDIT', 'SCHEDULE', 'PUBLISH', 'UNSCHEDULE', 'RIGHTS_EMAIL', 'REPUBLISH', 'REMOVE', 'SYSTEM_DUE')),
  CONSTRAINT ck_board_post_status_history__from_status CHECK (from_status IS NULL OR from_status IN ('DRAFT', 'SCHEDULED', 'PUBLISHED', 'HIDDEN_REVIEW', 'REMOVED')),
  CONSTRAINT ck_board_post_status_history__to_status CHECK (to_status IN ('DRAFT', 'SCHEDULED', 'PUBLISHED', 'HIDDEN_REVIEW', 'REMOVED')),
  CONSTRAINT ck_board_post_status_history__actor_type CHECK (actor_type IN ('ADMIN', 'SYSTEM')),
  CONSTRAINT ck_board_post_status_history__created_by CHECK (created_by ~ '^(system:(migration|scheduler|event-ingest|event-aggregate|outbox-worker)|(admin|user):v[1-9][0-9]*:[A-Za-z0-9_-]{43})$'),
  CONSTRAINT ck_board_post_status_history__updated_by CHECK (updated_by ~ '^(system:(migration|scheduler|event-ingest|event-aggregate|outbox-worker)|(admin|user):v[1-9][0-9]*:[A-Za-z0-9_-]{43})$'),
  CONSTRAINT ck_board_post_status_history__audit_time CHECK (updated_at >= created_at)
);

CREATE INDEX ix_board_post_status_history__post_created
  ON content.board_post_status_history (post_id, created_at DESC);
CREATE INDEX ix_board_post_status_history__reason_created
  ON content.board_post_status_history (reason_code, created_at DESC);

CREATE TABLE legal.policy_version (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  policy_type VARCHAR(20) NOT NULL,
  version_label VARCHAR(20) NOT NULL,
  title VARCHAR(200) NOT NULL,
  body_html TEXT NOT NULL,
  status VARCHAR(20) NOT NULL,
  effective_at TIMESTAMPTZ(3),
  ended_at TIMESTAMPTZ(3),
  created_by VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(100) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_policy_version__type_label UNIQUE (policy_type, version_label),
  CONSTRAINT ck_policy_version__policy_type CHECK (policy_type IN ('TERMS', 'PRIVACY')),
  CONSTRAINT ck_policy_version__title CHECK (length(btrim(title)) BETWEEN 1 AND 200),
  CONSTRAINT ck_policy_version__body_html CHECK (length(btrim(body_html)) > 0),
  CONSTRAINT ck_policy_version__status CHECK (status IN ('DRAFT', 'SCHEDULED', 'EFFECTIVE', 'RETIRED')),
  CONSTRAINT ck_policy_version__status_time CHECK (
    (status = 'DRAFT' AND effective_at IS NULL AND ended_at IS NULL)
    OR (status = 'SCHEDULED' AND effective_at IS NOT NULL AND ended_at IS NULL)
    OR (status = 'EFFECTIVE' AND effective_at IS NOT NULL AND ended_at IS NULL)
    OR (status = 'RETIRED' AND effective_at IS NOT NULL AND ended_at IS NOT NULL AND ended_at > effective_at)
  ),
  CONSTRAINT ck_policy_version__created_by CHECK (created_by ~ '^(system:(migration|scheduler|event-ingest|event-aggregate|outbox-worker)|(admin|user):v[1-9][0-9]*:[A-Za-z0-9_-]{43})$'),
  CONSTRAINT ck_policy_version__updated_by CHECK (updated_by ~ '^(system:(migration|scheduler|event-ingest|event-aggregate|outbox-worker)|(admin|user):v[1-9][0-9]*:[A-Za-z0-9_-]{43})$'),
  CONSTRAINT ck_policy_version__audit_time CHECK (updated_at >= created_at)
);

CREATE INDEX ix_policy_version__type_status_effective
  ON legal.policy_version (policy_type, status, effective_at DESC);
CREATE UNIQUE INDEX uq_policy_version__effective_one
  ON legal.policy_version (policy_type)
  WHERE status = 'EFFECTIVE';

CREATE TABLE analytics.raw_event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type VARCHAR(30) NOT NULL,
  anonymous_hmac BYTEA NOT NULL,
  session_hmac BYTEA NOT NULL,
  board_id BIGINT NOT NULL,
  post_id BIGINT,
  list_page INTEGER,
  item_count SMALLINT,
  dedupe_hmac BYTEA NOT NULL,
  occurred_at TIMESTAMPTZ(3) NOT NULL,
  aggregated_at TIMESTAMPTZ(3),
  created_by VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(100) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_raw_event__dedupe_hmac UNIQUE (dedupe_hmac),
  CONSTRAINT fk_raw_event__board FOREIGN KEY (board_id) REFERENCES content.board(id) ON DELETE RESTRICT,
  CONSTRAINT fk_raw_event__post FOREIGN KEY (post_id) REFERENCES content.board_post(id) ON DELETE RESTRICT,
  CONSTRAINT ck_raw_event__anonymous_hmac CHECK (octet_length(anonymous_hmac) = 32),
  CONSTRAINT ck_raw_event__session_hmac CHECK (octet_length(session_hmac) = 32),
  CONSTRAINT ck_raw_event__dedupe_hmac CHECK (octet_length(dedupe_hmac) = 32),
  CONSTRAINT ck_raw_event__list_page CHECK (list_page IS NULL OR list_page >= 1),
  CONSTRAINT ck_raw_event__item_count CHECK (item_count IS NULL OR item_count BETWEEN 0 AND 20),
  CONSTRAINT ck_raw_event__type CHECK (type IN ('FEED_VIEW', 'POST_VIEW', 'DETAIL_LIST_VIEW')),
  CONSTRAINT ck_raw_event__payload CHECK (
    (type = 'FEED_VIEW' AND post_id IS NULL AND list_page IS NOT NULL AND item_count IS NOT NULL)
    OR (type = 'POST_VIEW' AND post_id IS NOT NULL AND list_page IS NULL AND item_count IS NULL)
    OR (type = 'DETAIL_LIST_VIEW' AND post_id IS NOT NULL AND list_page IS NOT NULL AND item_count IS NOT NULL)
  ),
  CONSTRAINT ck_raw_event__created_by CHECK (created_by ~ '^(system:(migration|scheduler|event-ingest|event-aggregate|outbox-worker)|(admin|user):v[1-9][0-9]*:[A-Za-z0-9_-]{43})$'),
  CONSTRAINT ck_raw_event__updated_by CHECK (updated_by ~ '^(system:(migration|scheduler|event-ingest|event-aggregate|outbox-worker)|(admin|user):v[1-9][0-9]*:[A-Za-z0-9_-]{43})$'),
  CONSTRAINT ck_raw_event__audit_time CHECK (updated_at >= created_at)
);

CREATE INDEX ix_raw_event__occurred ON analytics.raw_event (occurred_at, id);
CREATE INDEX ix_raw_event__type_occurred ON analytics.raw_event (type, occurred_at);
CREATE INDEX ix_raw_event__anonymous_occurred ON analytics.raw_event (anonymous_hmac, occurred_at);
CREATE INDEX ix_raw_event__unaggregated ON analytics.raw_event (id) WHERE aggregated_at IS NULL;

CREATE TABLE analytics.daily_event_metric (
  event_date DATE NOT NULL,
  event_type VARCHAR(30) NOT NULL,
  board_id BIGINT NOT NULL,
  event_count BIGINT NOT NULL,
  unique_anonymous_count BIGINT NOT NULL,
  created_by VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(100) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_daily_event_metric PRIMARY KEY (event_date, event_type, board_id),
  CONSTRAINT fk_daily_event_metric__board FOREIGN KEY (board_id) REFERENCES content.board(id) ON DELETE RESTRICT,
  CONSTRAINT ck_daily_event_metric__event_type CHECK (event_type IN ('FEED_VIEW', 'POST_VIEW', 'DETAIL_LIST_VIEW')),
  CONSTRAINT ck_daily_event_metric__event_count CHECK (event_count >= 0),
  CONSTRAINT ck_daily_event_metric__unique_count CHECK (unique_anonymous_count >= 0),
  CONSTRAINT ck_daily_event_metric__created_by CHECK (created_by ~ '^(system:(migration|scheduler|event-ingest|event-aggregate|outbox-worker)|(admin|user):v[1-9][0-9]*:[A-Za-z0-9_-]{43})$'),
  CONSTRAINT ck_daily_event_metric__updated_by CHECK (updated_by ~ '^(system:(migration|scheduler|event-ingest|event-aggregate|outbox-worker)|(admin|user):v[1-9][0-9]*:[A-Za-z0-9_-]{43})$'),
  CONSTRAINT ck_daily_event_metric__audit_time CHECK (updated_at >= created_at)
);

CREATE TABLE ops.outbox_task (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type VARCHAR(30) NOT NULL,
  status VARCHAR(20) NOT NULL,
  aggregate_type VARCHAR(20) NOT NULL,
  aggregate_id BIGINT NOT NULL,
  payload JSONB NOT NULL,
  attempt_count SMALLINT NOT NULL DEFAULT 0,
  next_attempt_at TIMESTAMPTZ(3) NOT NULL,
  last_error_code VARCHAR(50),
  created_by VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(100) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_outbox_task__type CHECK (type IN ('CACHE_PURGE', 'OBJECT_DELETE_PUBLIC', 'OBJECT_DELETE_PRIVATE')),
  CONSTRAINT ck_outbox_task__status CHECK (status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'DEAD')),
  CONSTRAINT ck_outbox_task__aggregate_type CHECK (aggregate_type IN ('POST', 'IMAGE')),
  CONSTRAINT ck_outbox_task__type_aggregate CHECK (
    (type = 'CACHE_PURGE' AND aggregate_type = 'POST')
    OR (type IN ('OBJECT_DELETE_PUBLIC', 'OBJECT_DELETE_PRIVATE') AND aggregate_type = 'IMAGE')
  ),
  CONSTRAINT ck_outbox_task__aggregate_id CHECK (aggregate_id > 0),
  CONSTRAINT ck_outbox_task__payload CHECK (jsonb_typeof(payload) = 'object'),
  CONSTRAINT ck_outbox_task__attempt_count CHECK (attempt_count BETWEEN 0 AND 8),
  CONSTRAINT ck_outbox_task__created_by CHECK (created_by ~ '^(system:(migration|scheduler|event-ingest|event-aggregate|outbox-worker)|(admin|user):v[1-9][0-9]*:[A-Za-z0-9_-]{43})$'),
  CONSTRAINT ck_outbox_task__updated_by CHECK (updated_by ~ '^(system:(migration|scheduler|event-ingest|event-aggregate|outbox-worker)|(admin|user):v[1-9][0-9]*:[A-Za-z0-9_-]{43})$'),
  CONSTRAINT ck_outbox_task__audit_time CHECK (updated_at >= created_at)
);

CREATE INDEX ix_outbox_task__due
  ON ops.outbox_task (next_attempt_at, id)
  WHERE status IN ('PENDING', 'FAILED');
CREATE INDEX ix_outbox_task__running
  ON ops.outbox_task (updated_at, id)
  WHERE status = 'RUNNING';

CREATE TABLE ops.idempotency_request (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operation_scope VARCHAR(120) NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  request_hash BYTEA NOT NULL,
  response_status SMALLINT NOT NULL,
  response_body JSONB NOT NULL,
  resource_type VARCHAR(20) NOT NULL,
  resource_id BIGINT NOT NULL,
  expires_at TIMESTAMPTZ(3) NOT NULL,
  created_by VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(100) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_idempotency_request__actor_scope_key UNIQUE (created_by, operation_scope, idempotency_key),
  CONSTRAINT ck_idempotency_request__request_hash CHECK (octet_length(request_hash) = 32),
  CONSTRAINT ck_idempotency_request__response_status CHECK (response_status BETWEEN 200 AND 299),
  CONSTRAINT ck_idempotency_request__response_body CHECK (jsonb_typeof(response_body) = 'object'),
  CONSTRAINT ck_idempotency_request__resource_type CHECK (resource_type = 'POST'),
  CONSTRAINT ck_idempotency_request__resource_id CHECK (resource_id > 0),
  CONSTRAINT ck_idempotency_request__expires_at CHECK (expires_at > created_at),
  CONSTRAINT ck_idempotency_request__created_by CHECK (created_by ~ '^(system:(migration|scheduler|event-ingest|event-aggregate|outbox-worker)|(admin|user):v[1-9][0-9]*:[A-Za-z0-9_-]{43})$'),
  CONSTRAINT ck_idempotency_request__updated_by CHECK (updated_by ~ '^(system:(migration|scheduler|event-ingest|event-aggregate|outbox-worker)|(admin|user):v[1-9][0-9]*:[A-Za-z0-9_-]{43})$'),
  CONSTRAINT ck_idempotency_request__audit_time CHECK (updated_at >= created_at)
);

CREATE INDEX ix_idempotency_request__expires ON ops.idempotency_request (expires_at);
CREATE INDEX ix_idempotency_request__resource
  ON ops.idempotency_request (resource_type, resource_id, created_at DESC);
