services:
  api:
    logging: !override
      driver: syslog
      options:
        syslog-address: unixgram:///run/blariyo-logs/log.sock
        syslog-format: rfc3164
        tag: blariyo-api
        cache-disabled: 'true'
  web:
    logging: !override
      driver: syslog
      options:
        syslog-address: unixgram:///run/blariyo-logs/log.sock
        syslog-format: rfc3164
        tag: blariyo-web
        cache-disabled: 'true'
