version: '3.8'

services:
  mysql-test:
    image: mysql:8.0
    container_name: blariyo-mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blariyo_test
    ports:
      - "3307:3306"
    volumes:
      - ./init/mysql/scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5 